version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    environment: 
      - REACT_APP_MAPSAPIKEY
      - API_URL=http://localhost:8080
    volumes:
      - /app/node_modules
      - ./app:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - "dbUrl=mongodb://mongo:27017/test"
      # - "dbUrl=mongodb+srv://cluster0-nxwtn.azure.mongodb.net/test?retryWrites=true"
      # - MONGO_INITDB_ROOT_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - mongo
  mongo: 
    image: "mongo:latest"
    ports: 
      - "27017:27017"
  nginx: 
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:80"
    