version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - "dbUrl=mongodb://mongo:27017"
    volumes:
      - /app/node_modules
      - .:/app
  mongo: 
    image: "mongo:latest"
    ports: 
      - "27017:27017"