version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    environment: 
      - REACT_APP_MAPSAPIKEY
      - API_URL=http://35.240.215.253:8080
  api:
    build:
      context: ./api
    environment:
      - "dbUrl=mongodb://mongo:27017/test"
    volumes:
      - /app/node_modules
      - ./api:/app
  mongo: 
    image: "mongo:latest"
    ports: 
      - "27017:27017"
  nginx: 
    restart: always
    build: 
      context: ./nginx
    ports: 
      - "80:80"
    