version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    environment: 
      - REACT_APP_MAPSAPIKEY
      - API_URL=http://localhost:8080
  api:
    build:
      context: ./api
    environment:
      - "dbUrl=mongodb+srv://cluster0-nxwtn.azure.mongodb.net/test?retryWrites=true"
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - /app/node_modules
      - ./api:/app
  nginx: 
    restart: always
    build: 
      context: ./nginx
    ports: 
      - "80:80"
    